import pyautogui as py
import time

py.hotkey('win', 'r')
py.press('enter')
time.sleep(1)
py.write('cd desktop')
py.press('enter')
time.sleep(1)
py.write('cd relatorio')
py.press('enter')
time.sleep(1)
py.write('cd relatorio_ac')
py.press('enter')
time.sleep(1)
py.write('ren "fechamento.csv" "AR ESCRADPAR.csv"')
py.press('enter')
time.sleep(1)
py.write('ren "fechamento (1).csv" "AR ABS.csv"')
py.press('enter')
time.sleep(1)
py.write('ren "fechamento (2).csv" "AR WENEXT.csv"')
py.press('enter')
time.sleep(1)
py.write('ren "fechamento (3).csv" "AR SEVENREP.csv"')
py.press('enter')
time.sleep(1)
py.write('ren "fechamento (4).csv" "AR 1CERT.csv"')
py.press('enter')
time.sleep(1)
py.write('ren "fechamento (5).csv" "AR RENOVEAQUI.csv"')
py.press('enter')
time.sleep(1)
py.write('ren "fechamento (6).csv" "AR DIGITAL CERT.csv"')
py.press('enter')
time.sleep(1)
py.write('ren "fechamento (7).csv" "AR IDENTIDADE DIGITAL.csv"')
py.press('enter')
time.sleep(1)
py.write('ren "fechamento (8).csv" "AR QUALITY BAHIA.csv"')
py.press('enter')
time.sleep(1)
py.write('ren "fechamento (9).csv" "AR SOLUTEK PRIME.csv"')
py.press('enter')
time.sleep(1)
py.write('ren "fechamento (10).csv" "AR SOLUTEK.csv"')
py.press('enter')
time.sleep(1)
py.write('ren "fechamento (11).csv" "AR CERTPALMAS.csv"')
py.press('enter')
time.sleep(1)
py.write('ren "fechamento (12).csv" "AR POTIGUAR.csv"')
py.press('enter')
time.sleep(1)
py.write('ren "fechamento (13).csv" "AR CERT.csv"')
py.press('enter')
time.sleep(1)
py.write('ren "fechamento (14).csv" "AR UPSIGN.csv"')
py.press('enter')
time.sleep(1)
py.write('ren "fechamento (15).csv" "AR QC CERT.csv"')
py.press('enter')
time.sleep(1)
py.write('ren "fechamento (16).csv" "AR CERT IN.csv"')
py.press('enter')
time.sleep(1)
py.write('ren "fechamento (17).csv" "AR MR.csv"')
py.press('enter')
time.sleep(1)
py.write('ren "fechamento (18).csv" "AR CERTIFY.csv"')
py.press('enter')
time.sleep(1)
py.write('ren "fechamento (19).csv" "AR CERT SP.csv"')
py.press('enter')
time.sleep(1)
py.write('ren "fechamento (20).csv" "AR CERT TOTAL.csv"')
py.press('enter')
time.sleep(1)
py.write('ren "fechamento (21).csv" "AR A3.csv"')
py.press('enter')
time.sleep(1)
py.write('ren "fechamento (22).csv" "AR TERABYTE.csv"')
py.press('enter')
time.sleep(1)
py.write('ren "fechamento (23).csv" "AR IDBR.csv"')
py.press('enter')
time.sleep(1)
py.write('ren "fechamento (24).csv" "AR LTI.csv"')
py.press('enter')
time.sleep(1)
py.write('ren "fechamento (25).csv" "AR CERTIFICA SC.csv"')
py.press('enter')
time.sleep(1)
py.write('ren "fechamento (26).csv" "AR RUZZI.csv"')
py.press('enter')
time.sleep(1)
py.write('ren "fechamento (27).csv" "AR NW.csv"')
py.press('enter')
time.sleep(1)
py.write('ren "fechamento (28).csv" "AR TR TECNOLOGIA.csv"')
py.press('enter')
time.sleep(1)
py.write('ren "fechamento (29).csv" "AR IDEAL.csv"')
py.press('enter')
time.sleep(1)
py.write('ren "fechamento (30).csv" "AR CERTIFIQUE DIGITAL.csv"')
py.press('enter')
time.sleep(1)
py.write('ren "fechamento (31).csv" "AR SYSTEM.csv"')
py.press('enter')
time.sleep(1)
py.write('ren "fechamento (32).csv" "AR ID TECH.csv"')
py.press('enter')
time.sleep(1)

py.write('exit')
py.press('enter')
