import time
import pyautogui as py
import datetime

def transferir_pasta():

    py.hotkey('win', 'r')
    time.sleep(1)
    py.press('enter')
    time.sleep(2)
    py.write('cd Downloads')
    py.press('enter')
    time.sleep(2)
    py.write(r'move "C:\Users\Direta\Downloads\fechamento.csv" "C:\Users\Direta\Desktop\Relatorio"')
    time.sleep(1)
    py.press('enter')
    time.sleep(2)
    py.write('Todos')
    time.sleep(1)
    py.press('enter')
    time.sleep(1)
    py.write(r'move "C:\Users\Direta\Downloads\fechamento (1).csv" "C:\Users\Direta\Desktop\Relatorio"')
    time.sleep(1)
    py.press('enter')
    time.sleep(2)
    py.write('Todos')
    time.sleep(1)
    py.press('enter')
    time.sleep(1)
    py.write(r'move "C:\Users\Direta\Downloads\fechamento (2).csv" "C:\Users\Direta\Desktop\Relatorio"')
    time.sleep(1)
    py.press('enter')
    time.sleep(2)
    py.write('Todos')
    time.sleep(1)
    py.press('enter')
    time.sleep(1)
    py.write(r'move "C:\Users\Direta\Downloads\fechamento (3).csv" "C:\Users\Direta\Desktop\Relatorio"')
    time.sleep(1)
    py.press('enter')
    time.sleep(2)
    py.write('Todos')
    time.sleep(1)
    py.press('enter')
    time.sleep(1)
    py.write(r'move "C:\Users\Direta\Downloads\fechamento (4).csv" "C:\Users\Direta\Desktop\Relatorio"')
    time.sleep(1)
    py.press('enter')
    time.sleep(2)
    py.write('Todos')
    time.sleep(1)
    py.press('enter')
    time.sleep(1)
    py.write(r'move "C:\Users\Direta\Downloads\fechamento (5).csv" "C:\Users\Direta\Desktop\Relatorio"')
    time.sleep(1)
    py.press('enter')
    time.sleep(2)
    py.write('Todos')
    time.sleep(1)
    py.press('enter')
    time.sleep(1)
    py.write(r'move "C:\Users\Direta\Downloads\fechamento (6).csv" "C:\Users\Direta\Desktop\Relatorio"')
    time.sleep(1)
    py.press('enter')
    time.sleep(2)
    py.write('Todos')
    time.sleep(1)
    py.press('enter')
    time.sleep(1)
    py.write(r'move "C:\Users\Direta\Downloads\fechamento (7).csv" "C:\Users\Direta\Desktop\Relatorio"')
    time.sleep(1)
    py.press('enter')
    time.sleep(2)
    py.write('Todos')
    time.sleep(1)
    py.press('enter')
    time.sleep(1)
    py.write(r'move "C:\Users\Direta\Downloads\fechamento (8).csv" "C:\Users\Direta\Desktop\Relatorio"')
    time.sleep(1)
    py.press('enter')
    time.sleep(2)
    py.write('Todos')
    time.sleep(1)
    py.press('enter')
    time.sleep(1)
    py.write(r'move "C:\Users\Direta\Downloads\fechamento (9).csv" "C:\Users\Direta\Desktop\Relatorio"')
    time.sleep(1)
    py.press('enter')
    time.sleep(2)
    py.write('Todos')
    time.sleep(1)
    py.press('enter')
    time.sleep(1)
    py.write(r'move "C:\Users\Direta\Downloads\fechamento (10).csv" "C:\Users\Direta\Desktop\Relatorio"')
    time.sleep(1)
    py.press('enter')
    time.sleep(2)
    py.write('Todos')
    time.sleep(1)
    py.press('enter')
    time.sleep(1)

    py.write('exit')
    py.press('enter')